spring:
  application:
    name: item-service
  rabbitmq:
    host: 192.168.64.128
    port: 5672
    username: admin
    password: admin

#server:#  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
      
---
spring:
  profiles: item1

server:
  port: 8001
  
---
spring:
  profiles: item2

server:
  port: 8002
  
  
